# https://docs.github.com/zh/discussions/managing-discussions-for-your-community/creating-discussion-category-forms
body:
  - type: markdown
    attributes:
      value: |
         ## 须知
         ### 提问or反馈?
         请确保你的疑问应当是一个**疑问**而不是一个**反馈**。假如你的这个“疑问”来自于一串错误信息，那么你应该前往 [**此处**](https://github.com/simple-robot/simpler-robot/issues/new?template=bug-report.yml) 反馈这些错误。
         当然，如果你有很明确的目标，请继续。
         
         ### 确认
         在进行问题反馈前，请**确认**以下内容：
         1. 我已参阅过相关文档、注释。
         2. 我已确认 [issues](https://github.com/ForteScarlet/simpler-robot/issues) 或 [讨论区](https://github.com/orgs/simple-robot/discussions) 内没有类似/重复问题。
         3. 我已确认所述内容不涉及任何个人隐私或其他敏感信息。

         <hr />
         
  - type: dropdown
    id: language
    attributes:
      label: 选择此问题涉及的编程语言
      description:  (如果没有或无对应选项则选择'其他'后在描述中补充说明即可)
      options:
        - Java
        - Kotlin
        - 其他
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: 选择此问题涉及的组件库 (如果没有或无对应选项则在描述中补充说明即可)
      multiple: true
      options:
        - mirai
        - kook
        - QQ频道
        - 其他
  
  - type: textarea
    id: question
    attributes:
      label: 疑问描述
      description: 描述你的疑问
      placeholder: "例如: 怎么通过代码实现财富自由"
    validations:
      required: true
